services:
  qm1:
    image: icr.io/ibm-messaging/mq:latest
    container_name: QM1
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_USER: app
      MQ_APP_PASSWORD: passw0rd
      MQ_ADMIN_USER: admin
      MQ_ADMIN_PASSWORD: passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
